# Generated by Django 4.1.7 on 2023-05-06 18:11

import datetime
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('capa', models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/CapasLivros', location='/home/eudson/Sistema-Biblioteca/ApiBiblioteca/media//CapasLivros'), upload_to='')),
                ('autor', models.CharField(max_length=50)),
                ('editora', models.CharField(blank=True, max_length=50, null=True)),
                ('genero', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('nome', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/FotosUsuarios', location='/home/eudson/Sistema-Biblioteca/ApiBiblioteca/media//FotosUsuarios'), upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('emprestado', 'Emprestado'), ('atrasado', 'Atrasado'), ('devolvido', 'Devolvido')], default='emprestado', max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao', models.DateTimeField(default=datetime.datetime(2023, 6, 5, 18, 11, 3, 889316, tzinfo=datetime.timezone.utc))),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
