# Generated by Django 4.1.7 on 2023-05-26 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 15, 13, 15, 909243, tzinfo=datetime.timezone.utc)),
        ),
    ]
