# Generated by Django 4.1.7 on 2023-04-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='foto',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
