# Generated by Django 4.1.7 on 2023-05-06 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 18, 11, 21, 50297, tzinfo=datetime.timezone.utc)),
        ),
    ]
