# Generated by Django 4.1.7 on 2023-05-03 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 2, 18, 39, 1, 762135, tzinfo=datetime.timezone.utc)),
        ),
    ]
