# Generated by Django 4.1.7 on 2023-04-27 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_emprestimo_data_devolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 27, 18, 8, 6, 726947, tzinfo=datetime.timezone.utc)),
        ),
    ]
