# Generated by Django 4.1.7 on 2023-04-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_customuser_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('editora', models.CharField(max_length=50)),
                ('capa', models.CharField(max_length=50)),
            ],
        ),
    ]
