# Generated by Django 4.1.7 on 2023-05-05 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_emprestimo_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 19, 50, 50, 578608, tzinfo=datetime.timezone.utc)),
        ),
    ]
