# Generated by Django 4.1.7 on 2023-04-15 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
